name: CI

on:
  push:
    branches: [ "*" ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ "main", "master" ]
    paths-ignore:
      - '**.md'

jobs:
  ci:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [ 20.x ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint and type check
        run: npm run lint:full

      - name: Run stable tests
        run: |
          npm run test:unit -- tests/unit/core/pageManager.test.ts
          npm run test:unit -- tests/unit/tools/screenshotTool.test.ts
          npm run test:unit -- tests/unit/tools/consentTool.test.ts
          npm run test:unit -- tests/unit/tools/browserInteraction.test.ts
          npm run test:unit -- tests/unit/tools/scrapeArticleTool.test.ts

      - name: Build project
        run: npm run build

      #- name: Test Docker build
      #  run: docker build -f Dockerfile -t mcp-web-scraper:test .

      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const issue_number = context.payload.pull_request?.number;
            
            if (issue_number) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue_number,
                body: `❌ CI failed on commit ${context.sha.slice(0, 7)}. Please check the [workflow run](${context.payload.repository.html_url}/actions/runs/${context.runId}) for details.`
              });
            }